#!/bin/bash
sbatch 'bipedal_walker/adaptation_module/Adaptmod_ONMBP_tanh/jobscript_adaptmod_96neurons_0.001lr_0.0wd.sh'
sleep 3
sbatch 'bipedal_walker/adaptation_module/Adaptmod_ONMBP_tanh/jobscript_adaptmod_96neurons_0.001lr_0.0001wd.sh'
sleep 3
sbatch 'bipedal_walker/adaptation_module/Adaptmod_ONMBP_tanh/jobscript_adaptmod_96neurons_0.001lr_0.01wd.sh'
sleep 3
sbatch 'bipedal_walker/adaptation_module/Adaptmod_ONMBP_tanh/jobscript_adaptmod_96neurons_0.0005lr_0.0wd.sh'
sleep 3
sbatch 'bipedal_walker/adaptation_module/Adaptmod_ONMBP_tanh/jobscript_adaptmod_96neurons_0.0005lr_0.0001wd.sh'
sleep 3
sbatch 'bipedal_walker/adaptation_module/Adaptmod_ONMBP_tanh/jobscript_adaptmod_96neurons_0.0005lr_0.01wd.sh'
sleep 3
sbatch 'bipedal_walker/adaptation_module/Adaptmod_ONMBP_tanh/jobscript_adaptmod_96neurons_0.0001lr_0.0wd.sh'
sleep 3
sbatch 'bipedal_walker/adaptation_module/Adaptmod_ONMBP_tanh/jobscript_adaptmod_96neurons_0.0001lr_0.0001wd.sh'
sleep 3
sbatch 'bipedal_walker/adaptation_module/Adaptmod_ONMBP_tanh/jobscript_adaptmod_96neurons_0.0001lr_0.01wd.sh'
sleep 3
sbatch 'bipedal_walker/adaptation_module/Adaptmod_ONMBP_tanh/jobscript_adaptmod_96neurons_5e-05lr_0.0wd.sh'
sleep 3
sbatch 'bipedal_walker/adaptation_module/Adaptmod_ONMBP_tanh/jobscript_adaptmod_96neurons_5e-05lr_0.0001wd.sh'
sleep 3
sbatch 'bipedal_walker/adaptation_module/Adaptmod_ONMBP_tanh/jobscript_adaptmod_96neurons_5e-05lr_0.01wd.sh'
sleep 3
sbatch 'bipedal_walker/adaptation_module/Adaptmod_ONMBP_tanh/jobscript_adaptmod_96neurons_1e-05lr_0.0wd.sh'
sleep 3
sbatch 'bipedal_walker/adaptation_module/Adaptmod_ONMBP_tanh/jobscript_adaptmod_96neurons_1e-05lr_0.0001wd.sh'
sleep 3
sbatch 'bipedal_walker/adaptation_module/Adaptmod_ONMBP_tanh/jobscript_adaptmod_96neurons_1e-05lr_0.01wd.sh'
